name: nutro
description: Flutter + Firebase email/password + Google Sign-In demo
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0

  # Google Sign-In
  google_sign_in: ^6.1.0

  # UI helpers
  flutter_signin_button: ^2.0.0

  # Optional (for nicer forms)
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
