// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYGLZjsRfdglM-e9jdPS7nN_fm3ye6y4E',
    appId: '1:800797352751:web:19a063dff6ffe9b541f7da',
    messagingSenderId: '800797352751',
    projectId: 'nutro-c99d7',
    authDomain: 'nutro-c99d7.firebaseapp.com',
    storageBucket: 'nutro-c99d7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkGAHAmyEzYN_gcA7KcIDO10Ac6k4r9ho',
    appId: '1:800797352751:android:cd10658fcb96b96941f7da',
    messagingSenderId: '800797352751',
    projectId: 'nutro-c99d7',
    storageBucket: 'nutro-c99d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpgI_GdjykSpNPMqVZ5XPkfE7WhHbNtak',
    appId: '1:800797352751:ios:be2237eb55b9d9dd41f7da',
    messagingSenderId: '800797352751',
    projectId: 'nutro-c99d7',
    storageBucket: 'nutro-c99d7.firebasestorage.app',
    androidClientId: '800797352751-4i6r4pilhd28h9o4ptj0idhljdccb69l.apps.googleusercontent.com',
    iosClientId: '800797352751-fs677e7o1k8kr7beiir7a24g29usqkuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpgI_GdjykSpNPMqVZ5XPkfE7WhHbNtak',
    appId: '1:800797352751:ios:be2237eb55b9d9dd41f7da',
    messagingSenderId: '800797352751',
    projectId: 'nutro-c99d7',
    storageBucket: 'nutro-c99d7.firebasestorage.app',
    androidClientId: '800797352751-4i6r4pilhd28h9o4ptj0idhljdccb69l.apps.googleusercontent.com',
    iosClientId: '800797352751-fs677e7o1k8kr7beiir7a24g29usqkuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYGLZjsRfdglM-e9jdPS7nN_fm3ye6y4E',
    appId: '1:800797352751:web:0c77db8178f4604641f7da',
    messagingSenderId: '800797352751',
    projectId: 'nutro-c99d7',
    authDomain: 'nutro-c99d7.firebaseapp.com',
    storageBucket: 'nutro-c99d7.firebasestorage.app',
  );
}
